@extends('layouts.site', ['title' => 'About Us', 'description' => 'Learn how CodexnIndia turns ideas into useful digital products.'])
@section('content')
@include('partials.project-hero', [
    'heroProject' => [
        'breadcrumb' => 'Home › About Us',
        'eyebrow' => 'ABOUT CODEXNINDIA',
        'title' => 'We Turn Ideas Into',
        'titleAccent' => 'Digital Reality',
        'description' => 'We are a focused technology and growth studio helping businesses move with clarity, confidence, and momentum.',
        'image' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=88',
        'floatingLabel' => 'About',
        'floatingTitle' => "Passionate\nTeam\nTogether",
        'statNumber' => '5+ Years',
        'statLabel' => 'Industry Experience',
    ],
])

<section class="py-5"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-6"><p class="eyebrow">Why we exist</p><h2 class="h2 fw-bold">Technology should feel<br><span class="text-brand">clear and human.</span></h2><p class="text-secondary mt-3">CodexnIndia brings product thinking, sharp design, and dependable engineering into one partner. We stay close to the work, communicate openly, and build around outcomes rather than noise.</p><p class="text-secondary">From a first website to an internal software platform, our job is to make the next step feel possible.</p></div><div class="col-lg-6"><img class="about-page-image rounded-4 shadow-sm" src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1100&q=85" alt="CodexnIndia team collaborating"></div></div></div></section>
<section class="py-5 bg-light"><div class="container"><div class="row g-3"><div class="col-md-4"><article class="info-card h-100 p-4 bg-white border rounded-4"><i class="bi bi-compass text-brand fs-2"></i><h3 class="h5 fw-bold mt-4">Our Mission</h3><p class="small text-secondary mb-0">Make great technology more accessible to growing businesses.</p></article></div><div class="col-md-4"><article class="info-card h-100 p-4 bg-white border rounded-4"><i class="bi bi-eye text-brand fs-2"></i><h3 class="h5 fw-bold mt-4">Our Vision</h3><p class="small text-secondary mb-0">Become the trusted digital partner behind India’s next generation of companies.</p></article></div><div class="col-md-4"><article class="info-card h-100 p-4 bg-white border rounded-4"><i class="bi bi-stars text-brand fs-2"></i><h3 class="h5 fw-bold mt-4">Our Values</h3><p class="small text-secondary mb-0">Curiosity, integrity, clear communication, and work that creates momentum.</p></article></div></div></div></section>
<section class="py-5"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-5"><p class="eyebrow">Our future USP</p><h2 class="h2 fw-bold">A workspace where<br><span class="text-brand">you stay in control.</span></h2><p class="text-secondary">We are building a private client workspace for project chat, progress flow, approvals, shared notes, and live updates. Your project will never feel like a black box.</p><a class="btn btn-brand" href="{{ route('home') }}#contact">Join the early access list →</a></div><div class="col-lg-7"><div class="workspace-page-card p-4 border rounded-4 shadow-sm"><div class="d-flex justify-content-between"><strong>Client workspace</strong><span class="workspace-badge">Coming soon</span></div><div class="progress mt-4" style="height:8px"><div class="progress-bar bg-brand" style="width:72%"></div></div><div class="row g-3 mt-2"><div class="col-sm-4"><small class="text-secondary d-block">Project flow</small><strong>72% active</strong></div><div class="col-sm-4"><small class="text-secondary d-block">Team chat</small><strong>12 updates</strong></div><div class="col-sm-4"><small class="text-secondary d-block">Shared notes</small><strong>7 ideas</strong></div></div></div></div></div></div></section>
<section class="py-5 bg-light"><div class="container"><div class="text-center mb-4"><p class="eyebrow">Google reviews</p><h2 class="h2 fw-bold">Trusted by teams building <span class="text-brand">what’s next.</span></h2></div><div class="row row-cols-1 row-cols-md-3 g-3"><div class="col"><article class="review-card h-100 bg-white border rounded-3 p-4"><div class="stars mb-3">★★★★★</div><p class="small text-secondary">“Clear thinking, fast communication, and a website that finally feels like our business.”</p><b class="small">Aarav Mehta</b></article></div><div class="col"><article class="review-card h-100 bg-white border rounded-3 p-4"><div class="stars mb-3">★★★★★</div><p class="small text-secondary">“They stayed involved after launch and helped our team keep improving.”</p><b class="small">Priya Sharma</b></article></div><div class="col"><article class="review-card h-100 bg-white border rounded-3 p-4"><div class="stars mb-3">★★★★★</div><p class="small text-secondary">“A thoughtful partner from first idea to measurable growth.”</p><b class="small">Rohan Kapoor</b></article></div></div></div></section>
@endsection
