@php
    $content = [
        'website-development' => ['eyebrow' => 'WEBSITE DEVELOPMENT', 'hero_title' => 'Powerful Websites for Your Business Growth', 'hero_text' => 'We design and develop modern, responsive, and high-performing websites that not only look great but also help you generate leads, boost sales, and grow your brand online.', 'hero_image' => 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1400&q=88', 'types_title' => 'Types of Websites We Build', 'types' => [['bi-globe2', 'Business Websites', 'Professional websites to establish your brand and attract more customers.', ['Corporate Websites', 'Small Business Websites', 'Service Based Websites', 'Landing Pages']], ['bi-cart3', 'E-commerce Websites', 'Feature-rich online stores to help you sell products and grow revenue.', ['Custom E-commerce Stores', 'Payment Gateway Integration', 'Product Management', 'Secure & Scalable']], ['bi-code-slash', 'Custom Web Applications', 'Tailored web applications built to automate processes and solve business challenges.', ['SaaS Applications', 'Web Portals', 'CRM & ERP Systems', 'API Integrations']], ['bi-gear-wide-connected', 'Redesign & Maintenance', 'Give your existing website a fresh look and keep it running smoothly with support.', ['Website Redesign', 'Performance Optimization', 'Bug Fixes & Updates', 'Ongoing Support']]], 'media' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=85'],
        'seo' => ['eyebrow' => 'SEO SERVICES', 'hero_title' => 'Get Found by the Right Customers', 'hero_text' => 'Build search visibility with technical SEO, useful content, and a clear growth strategy that turns organic traffic into qualified leads.', 'hero_image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=88', 'types_title' => 'SEO Solutions We Deliver', 'types' => [['bi-search', 'Technical SEO', 'Make your website easier for search engines to crawl, understand, and rank.', ['Site Audits', 'Core Web Vitals', 'Schema Markup', 'Crawl Improvements']], ['bi-file-earmark-text', 'Content Strategy', 'Create useful content that answers real customer questions and earns trust.', ['Keyword Research', 'Topic Clusters', 'Content Briefs', 'Editorial Planning']], ['bi-graph-up-arrow', 'Local SEO', 'Reach nearby customers when they are ready to contact your business.', ['Google Business Profile', 'Local Citations', 'Review Strategy', 'Location Pages']], ['bi-bar-chart-line', 'SEO Reporting', 'Track the signals that matter and make better decisions every month.', ['Rank Tracking', 'Traffic Reports', 'Lead Attribution', 'Action Plans']]], 'media' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=85'],
        'software-development' => ['eyebrow' => 'SOFTWARE DEVELOPMENT', 'hero_title' => 'Software That Makes Your Business Better', 'hero_text' => 'We build custom dashboards, portals, automations, and software products that simplify complex work and give growing teams more control.', 'hero_image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=88', 'types_title' => 'Software We Build', 'types' => [['bi-window-stack', 'Business Software', 'Replace disconnected tools with software designed around your actual workflow.', ['Admin Panels', 'Operations Systems', 'Approval Workflows', 'Reports']], ['bi-boxes', 'Web Applications', 'Create reliable browser-based products for customers, teams, and partners.', ['Customer Portals', 'SaaS Products', 'User Accounts', 'API Integrations']], ['bi-phone', 'Mobile-ready Products', 'Give users a consistent experience across devices and screen sizes.', ['Responsive Interfaces', 'Mobile UX', 'Notifications', 'Secure Access']], ['bi-shield-check', 'Maintenance & Support', 'Keep your product secure, reliable, and ready for the next stage of growth.', ['Bug Fixes', 'Security Updates', 'Performance Reviews', 'Ongoing Support']]], 'media' => 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85'],
        'branding' => ['eyebrow' => 'BRANDING & DESIGN', 'hero_title' => 'Build a Brand People Remember', 'hero_text' => 'Create a clear, consistent identity that gives your business confidence across every screen, campaign, and customer touchpoint.', 'hero_image' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1400&q=88', 'types_title' => 'Brand Experiences We Create', 'types' => [['bi-palette', 'Logo & Identity', 'Build a visual identity that feels distinct, useful, and ready to grow.', ['Logo Design', 'Color Systems', 'Typography', 'Brand Guidelines']], ['bi-vector-pen', 'UI/UX Design', 'Turn complex ideas into intuitive and enjoyable digital experiences.', ['User Flows', 'Wireframes', 'Prototypes', 'Design Systems']], ['bi-megaphone', 'Marketing Creatives', 'Make your campaigns recognizable with creative assets built for action.', ['Social Media Creatives', 'Ad Design', 'Campaign Assets', 'Presentations']], ['bi-stars', 'Brand Strategy', 'Clarify your position, voice, audience, and reason to choose you.', ['Brand Positioning', 'Audience Research', 'Messaging', 'Launch Direction']]], 'media' => 'https://images.unsplash.com/photo-1558655146-6c2e7b5f9e8e?auto=format&fit=crop&w=900&q=85'],
    ];
    $page = $content[$slug] ?? $content['website-development'];
@endphp
@extends('layouts.site', ['title' => $service[0], 'description' => $page['hero_text']])
@section('content')
<section class="services-reference-hero">
    <div class="container">
        <div class="row align-items-center g-0">
            <div class="col-lg-6 hero-reference-copy">
                <p class="services-breadcrumb">Home <span class="breadcrumb-sep">›</span> Services <span class="breadcrumb-sep">›</span> {{ $service[0] }}</p>
                <p class="eyebrow">{{ $page['eyebrow'] }}</p>
                <h1>{{ $page['hero_title'] }}</h1>
                <p class="lead">{{ $page['hero_text'] }}</p>
            </div>
            <div class="col-lg-6 services-reference-art">
                <div class="services-orange-shape"></div>
                <div class="services-scribble">Ideas<br>Code<br><em>Growth</em></div>
                <img class="services-developer" src="{{ $page['hero_image'] }}" alt="{{ $service[0] }} preview">
                <div class="services-hero-card">
                    <span>Your</span>
                    <strong>Technology<br>Partner<br>in Growth</strong>
                </div>
                <div class="services-project-card">
                    <strong>100+</strong>
                    <small>Projects Delivered</small>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="service-types" class="service-types-section py-5"><div class="container"><p class="eyebrow mb-2">{{ $page['eyebrow'] }}</p>@if($slug === 'website-development')<h2>Types of Websites <span>We Build</span></h2>@else<h2>{{ $page['types_title'] }}</h2>@endif<div class="row g-3 mt-2">@foreach($page['types'] as $type)<div class="col-md-6 col-xl-3"><article class="service-type-card service-type-{{ $loop->iteration }} h-100"><i class="bi {{ $type[0] }}"></i><h3>{{ $type[1] }}</h3><p>{{ $type[2] }}</p><ul>@foreach($type[3] as $item)<li><i class="bi bi-check-circle-fill"></i>{{ $item }}</li>@endforeach</ul><a href="{{ route('contact') }}">Learn More <i class="bi bi-arrow-right"></i></a></article></div>@endforeach</div></div></section>
<section class="service-process-section py-5"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-5"><div class="service-process-image"><img src="{{ $page['media'] }}" alt="{{ $service[0] }} process"><span><i class="bi bi-play-fill"></i> Watch Our Process</span></div></div><div class="col-lg-7"><p class="eyebrow">OUR DEVELOPMENT PROCESS</p><h2>From Idea to <span>Launch</span></h2><p class="text-secondary">We follow a simple and transparent process to ensure your {{ strtolower($service[0]) }} is built with purpose.</p><div class="service-steps">@foreach([['01','Discover','Understand your goals'],['02','Plan','Strategy & wireframing'],['03','Design','Modern & engaging UI/UX'],['04','Develop','Clean & scalable build'],['05','Launch','Testing & go live']] as $step)<div><b>{{ $step[0] }}</b><i class="bi {{ ['bi-search','bi-file-earmark-text','bi-rocket','bi-code-slash','bi-send'][$loop->index] }}"></i><strong>{{ $step[1] }}</strong><small>{{ $step[2] }}</small></div>@endforeach</div></div></div></div></section>
<section class="service-why-section py-5"><div class="container"><div class="row g-5"><div class="col-lg-6"><p class="eyebrow">WHY CHOOSE CODEXNINDIA?</p><h2>We build with <span>purpose.</span></h2><p class="text-secondary">We combine technology, creativity, and strategy to deliver solutions that create real business value.</p><div class="service-why-grid">@foreach([['bi-bullseye','Result-Oriented Approach','Focused on your business growth'],['bi-clock','Timely Delivery','On-time project completion'],['bi-palette','Modern & Clean Design','User-friendly and visually appealing'],['bi-headset','Dedicated Support','We are always here to help']] as $reason)<div><i class="bi {{ $reason[0] }}"></i><span><strong>{{ $reason[1] }}</strong><small>{{ $reason[2] }}</small></span></div>@endforeach</div></div><div class="col-lg-6"><div class="service-faq"><div class="d-flex justify-content-between align-items-center"><h3>Frequently Asked Questions</h3><a href="{{ route('home') }}#contact">View All â†’</a></div>@foreach(['How long does it take to develop?','Will my website be mobile-friendly?','Do you provide domain and hosting?','Can I update the website myself?'] as $question)<details><summary>{{ $question }} <i class="bi bi-plus-lg"></i></summary><p>We shape the answer around your goals, scope, and project requirements during the consultation.</p></details>@endforeach</div></div></div></div></section>
<section class="service-final-cta py-4"><div class="container"><div><h2>Ready to Build Your <span>{{ $service[0] }}?</span></h2><p>Let's discuss your project and create something amazing together.</p></div><a href="{{ route('home') }}#contact" class="btn btn-light">Get a Free Consultationã€€â†’</a><em>Big Ideas<br>Better Tomorrow</em></div></section><section class="py-4"><div class="container"><div class="row row-cols-2 row-cols-lg-4 stats-reference g-0 border-top border-bottom text-center"><div class="col"><strong>100+</strong><small>Projects Delivered</small></div><div class="col"><strong>50+</strong><small>Happy Clients</small></div><div class="col"><strong>5+</strong><small>Years Experience</small></div><div class="col"><strong>24/7</strong><small>Support</small></div></div></div></section>
@endsection


