@php
    $client = $client ?? 'dreamhome-real-estate';
    $clientNames = ['dreamhome-real-estate' => 'DreamHome Real Estate Pvt. Ltd.', 'nexus-property-group' => 'Nexus Property Group', 'medicore-health' => 'MediCore Health', 'northstar-growth' => 'Northstar Growth'];
    $clientName = $clientNames[$client] ?? $clientNames['dreamhome-real-estate'];
@endphp
@extends('layouts.team', ['title' => $clientName, 'description' => 'Client overview, projects, tasks, activity, and team members.'])
@section('content')
<section class="dashboard-content client-detail-page">
    <div class="client-breadcrumb"><a href="{{ route('team.clients') }}">Clients</a><i class="bi bi-chevron-right"></i><span>{{ $clientName }}</span><i class="bi bi-chevron-right"></i><span>Client Details</span></div>
    <div class="client-detail-head"><div class="client-heading"><div class="client-avatar">{{ strtoupper(substr($clientName, 0, 2)) }}</div><div><h1>{{ $clientName }} <span class="client-active"><i class="bi bi-circle-fill"></i> Active</span></h1><p>Client Account <span>|</span> Added to CodexnIndia <span>|</span> Active relationship</p></div></div><div class="client-head-actions"><a href="{{ route('team.clients.edit', $client) }}" class="btn btn-light border"><i class="bi bi-pencil me-1"></i> Edit Client</a><button class="btn btn-light border"><i class="bi bi-file-earmark-text me-1"></i> Create Proposal</button><a href="{{ route('team.projects.create') }}" class="btn btn-brand">+ Add New Project</a></div></div>
    <nav class="client-tabs"><a class="active" href="#overview"><i class="bi bi-record-circle"></i> Overview</a><a href="#projects"><i class="bi bi-briefcase"></i> Projects</a><a href="#requirements"><i class="bi bi-clipboard-check"></i> Requirements</a><a href="#content-plan"><i class="bi bi-pencil-square"></i> Content Plan</a><a href="#seo"><i class="bi bi-link-45deg"></i> SEO & Keywords</a><a href="#ads"><i class="bi bi-megaphone"></i> Ads Plan</a><a href="#invoices"><i class="bi bi-file-earmark-text"></i> Invoices</a><a href="#activity"><i class="bi bi-list-task"></i> Activity</a></nav>
    <div class="row g-3 mt-1" id="overview"><div class="col-lg-4"><section class="client-panel h-100"><h2>Client Information</h2><dl><div><dt><i class="bi bi-person"></i> Client Name</dt><dd>DreamHome Real Estate Pvt. Ltd.</dd></div><div><dt><i class="bi bi-person-badge"></i> Primary Contact</dt><dd>Rohit Sharma (Manager)</dd></div><div><dt><i class="bi bi-envelope"></i> Email</dt><dd><a href="mailto:rohit@dreamhome.in">rohit@dreamhome.in</a></dd></div><div><dt><i class="bi bi-telephone"></i> Phone</dt><dd>+91 98765 43210</dd></div><div><dt><i class="bi bi-globe"></i> Website</dt><dd><a href="https://dreamhome.in">https://dreamhome.in</a></dd></div><div><dt><i class="bi bi-geo-alt"></i> Address</dt><dd>Sector 62, Noida, Uttar Pradesh, India</dd></div><div><dt><i class="bi bi-pencil-square"></i> Notes</dt><dd>Long term client, interested in digital growth and brand presence.</dd></div></dl></section></div><div class="col-lg-5"><section class="client-panel h-100"><div class="client-panel-title"><h2>Quick Stats</h2><select><option>Last 6 Months</option><option>Last 12 Months</option></select></div><div class="client-stats-grid"><span><i class="bi bi-folder"></i><b>4</b><small>Total Projects</small></span><span><i class="bi bi-file-check"></i><b>12</b><small>Total Tasks</small></span><span><i class="bi bi-image"></i><b>28</b><small>Content Items</small></span><span><i class="bi bi-search"></i><b>56</b><small>Keywords</small></span><span><i class="bi bi-megaphone"></i><b>24</b><small>Ad Creatives</small></span><span><i class="bi bi-file-earmark-text"></i><b>3</b><small>Invoices</small></span></div></section></div><div class="col-lg-3"><section class="client-panel h-100"><h2>Client Actions</h2><div class="client-actions"><button><i class="bi bi-sticky"></i> Add Note</button><button><i class="bi bi-calendar-event"></i> Schedule Meeting</button><button><i class="bi bi-envelope"></i> Send Email</button><button><i class="bi bi-upload"></i> Upload Document</button><button><i class="bi bi-check2-circle"></i> Create Task</button></div></section></div></div>
    <section class="client-panel mt-3" id="projects"><div class="client-panel-title"><h2>Projects & Services</h2><a href="{{ route('team.projects.create') }}" class="btn btn-sm btn-light border">+ Add Service / Project</a></div><div class="client-project-list">@foreach([['bi-window-stack','01','Website Development','Business website with property listings and enquiry form.','In Progress','15 Sep 2025','30 Oct 2025','₹80,000'],['bi-megaphone','02','Digital Marketing','SEO, Google Ads and Social Media Marketing.','Planning','01 Oct 2025','—','₹40,000 / month'],['bi-boxes','03','Software Development','Custom CRM for lead management.','Not Started','—','—','₹1,20,000'],['bi-palette','04','Branding & Design','Logo, Brochure, Social Media Creatives.','In Progress','10 Sep 2025','25 Sep 2025','₹25,000']] as $project)<div class="client-project-row"><i class="bi {{ $project[0] }}"></i><b>{{ $project[1] }}</b><div><strong>{{ $project[2] }}</strong><small>{{ $project[3] }}</small></div><span class="project-state {{ Str::slug($project[4]) }}">{{ $project[4] }}</span><small>{{ $project[5] }}</small><small>{{ $project[6] }}</small><strong>{{ $project[7] }}</strong><button type="button" class="open-service-brief" data-brief="{{ Str::slug($project[2]) }}">Open Brief <i class="bi bi-arrow-right"></i></button></div>@endforeach</div></section>
    <section class="client-panel service-brief-panel mt-3" id="service-brief"><div class="client-panel-title"><h2>Service Brief</h2><span class="client-payment-rule">Current focus: Website Development</span></div><div class="service-brief-grid"><div><small>What service is running?</small><strong id="briefService">Website Development</strong><p id="briefScope">Business website with property listings, enquiry form, mobile responsive pages, and SEO-ready structure.</p></div><div><small>What does the client want?</small><strong id="briefGoal">More qualified property enquiries</strong><p>Make the brand trustworthy, explain properties clearly, and create a simple path from visit to enquiry.</p></div><div><small>Delivery model</small><strong id="briefModel">Strategy → Design → Develop → Launch</strong><p>Weekly review, milestone approvals, and a final handover with training.</p></div><div><small>Key points</small><ul id="briefPoints"><li>Responsive website for mobile and desktop</li><li>Property listing and enquiry flow</li><li>SEO basics, analytics, and secure hosting</li></ul></div></div></section>
    <div class="row g-3 mt-0"><div class="col-lg-7"><section class="client-panel"><div class="client-panel-title"><h2>Payment Flow</h2><span class="client-payment-rule">50% advance / 50% final</span></div><div class="payment-summary"><div><small>Total Contract Value</small><strong>₹2,65,000</strong></div><div><small>Advance Received</small><strong class="payment-paid">₹1,32,500</strong><span>50% paid</span></div><div><small>Balance Due</small><strong class="payment-due">₹1,32,500</strong><span>Due after completion</span></div></div><div class="payment-timeline"><div class="complete"><i class="bi bi-check-circle-fill"></i><span><strong>Advance invoice paid</strong><small>INV-2025-001 · 15 Sep 2025 · ₹1,32,500</small></span><b>Paid</b></div><div><i class="bi bi-circle"></i><span><strong>Final payment</strong><small>Due after project completion · Website Development</small></span><b>Pending</b></div></div></section></div><div class="col-lg-5"><section class="client-panel"><div class="client-panel-title"><h2>Invoices & Payments</h2><a href="#">View All →</a></div><div class="invoice-list">@foreach([['INV-2025-001','Website Development - Advance','₹1,32,500','Paid','15 Sep 2025'],['INV-2025-002','Website Development - Final','₹1,32,500','Pending','30 Oct 2025'],['INV-2025-003','Digital Marketing - Monthly','₹40,000','Pending','01 Oct 2025']] as $invoice)<div class="invoice-row"><i class="bi bi-file-earmark-text"></i><span><strong>{{ $invoice[0] }}</strong><small>{{ $invoice[1] }} · {{ $invoice[4] }}</small></span><b>{{ $invoice[2] }}</b><em class="{{ Str::slug($invoice[3]) }}">{{ $invoice[3] }}</em></div>@endforeach</div><button class="btn btn-sm btn-outline-brand rounded-pill mt-3">+ Create Invoice</button></section></div></div>
    <div class="row g-3 mt-0"><div class="col-lg-4"><section class="client-panel"><div class="client-panel-title"><h2>Upcoming Tasks</h2><a href="#">View All →</a></div>@foreach(['Design homepage layout','Prepare SEO keyword list','Create social media calendar','Client meeting (project review)'] as $task)<label class="client-task"><input type="checkbox"> <span>{{ $task }}</span><time>{{ ['15 Sep','16 Sep','18 Sep','20 Sep'][$loop->index] }}</time></label>@endforeach</section></div><div class="col-lg-4"><section class="client-panel"><div class="client-panel-title"><h2>Recent Activity</h2><a href="#">View All →</a></div><div class="client-activity">@foreach([['Project created','Website Development','2 hours ago'],['Requirement updated','Added 5 new pages','5 hours ago'],['New task assigned','Create homepage design','1 day ago'],['Client commented','Please add search filter in property listing.','2 days ago']] as $activity)<div><i></i><span><strong>{{ $activity[0] }}</strong><small>{{ $activity[1] }}</small></span><time>{{ $activity[2] }}</time></div>@endforeach</div></section></div><div class="col-lg-4"><section class="client-panel"><div class="client-panel-title"><h2>Team Members</h2><a href="{{ route('team.members') }}">Manage Team →</a></div>@foreach([['Aman Gupta','Project Manager'],['Neha Singh','Digital Marketing'],['Vikram Yadav','UI/UX Designer'],['Priya Verma','Content Writer']] as $person)<div class="client-person"><span>{{ strtoupper(substr($person[0],0,1)) }}</span><div><strong>{{ $person[0] }}</strong><small>{{ $person[1] }}</small></div><em>Website, Software</em></div>@endforeach</section></div></div>
</section>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const briefs = {
        'website-development': { service: 'Website Development', scope: 'Business website with property listings, enquiry form, mobile responsive pages, and SEO-ready structure.', goal: 'More qualified property enquiries', model: 'Strategy → Design → Develop → Launch', points: ['Responsive website for mobile and desktop', 'Property listing and enquiry flow', 'SEO basics, analytics, and secure hosting'] },
        'digital-marketing': { service: 'Digital Marketing', scope: 'SEO, Google Ads, social media campaigns, landing pages, and monthly reporting.', goal: 'More visibility and consistent qualified leads', model: 'Audit → Campaign → Optimise → Report', points: ['SEO and keyword strategy', 'Google Ads and social campaigns', 'Lead tracking and monthly reporting'] },
        'software-development': { service: 'Software Development', scope: 'Custom CRM for lead management, task workflows, reporting, and secure team access.', goal: 'Organise leads and reduce manual work', model: 'Discover → Plan → Build → Test → Handover', points: ['Custom dashboard and CRM modules', 'Role-based access and workflow automation', 'Reports, integrations, and support'] },
        'branding-design': { service: 'Branding & Design', scope: 'Logo, brochure, social media creatives, and a consistent visual identity.', goal: 'Look professional and become easier to remember', model: 'Discover → Direction → Design → Deliver', points: ['Logo and identity system', 'Marketing and social creatives', 'Brand guidelines and reusable assets'] }
    };
    document.querySelectorAll('.open-service-brief').forEach(function (button) { button.addEventListener('click', function () { const brief = briefs[button.dataset.brief]; if (!brief) return; document.getElementById('briefService').textContent = brief.service; document.getElementById('briefScope').textContent = brief.scope; document.getElementById('briefGoal').textContent = brief.goal; document.getElementById('briefModel').textContent = brief.model; document.getElementById('briefPoints').innerHTML = brief.points.map(function (point) { return '<li>' + point + '</li>'; }).join(''); document.getElementById('service-brief').scrollIntoView({ behavior: 'smooth', block: 'start' }); }); });
});
</script>
@endsection
