@php
    $client = $client ?? 'dreamhome-real-estate';
    $clients = ['dreamhome-real-estate' => ['DreamHome Real Estate Pvt. Ltd.', 'Rohit Sharma (Manager)', 'rohit@dreamhome.in', '+91 98765 43210', 'Real Estate', 'New Delhi, India'], 'nexus-property-group' => ['Nexus Property Group', 'Amit Sharma', 'amit@nexusproperty.in', '+91 98765 11111', 'Real Estate', 'Gurugram, India'], 'medicore-health' => ['MediCore Health', 'Neha Singh', 'neha@medicore.in', '+91 98765 22222', 'Healthcare', 'Mumbai, India'], 'northstar-growth' => ['Northstar Growth', 'Priya Verma', 'priya@northstar.in', '+91 98765 33333', 'Marketing', 'Bengaluru, India']];
    $data = $clients[$client] ?? $clients['dreamhome-real-estate'];
@endphp
@extends('layouts.team', ['title' => 'Edit Client', 'description' => 'Edit client information, project dates, pricing, and payment settings.'])
@section('content')
<section class="dashboard-content">
    <div class="dashboard-welcome-row align-items-center justify-content-between"><div><h1>Edit Client</h1><p>Update client information and correct any project or payment details.</p></div><div class="d-flex gap-2 ms-auto" style="grid-column: 3; justify-self: end;"><a href="{{ route('team.clients.detail', $client) }}" class="btn btn-outline-secondary rounded-pill px-4 py-2">Back to Details</a></div></div>
    <section class="dashboard-card mt-3 p-4"><form>
        <h2 class="h5 fw-bold mb-3">Client Information</h2><div class="row g-3">
            <div class="col-md-6"><label class="form-label">Company / Client Name</label><input class="form-control" value="{{ $data[0] }}"></div><div class="col-md-6"><label class="form-label">Industry</label><select class="form-select"><option selected>{{ $data[4] }}</option><option>Healthcare</option><option>Finance</option><option>Marketing</option><option>Technology</option></select></div>
            <div class="col-md-6"><label class="form-label">Primary Contact</label><input class="form-control" value="{{ $data[1] }}"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" value="{{ $data[2] }}"></div>
            <div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" value="{{ $data[3] }}"></div><div class="col-md-6"><label class="form-label">Website</label><input class="form-control" value="https://dreamhome.in"></div>
            <div class="col-12"><label class="form-label">Address</label><textarea class="form-control" rows="2">{{ $data[5] }}</textarea></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" rows="4">Long term client, interested in digital growth and brand presence.</textarea></div>
            <div class="col-md-4"><label class="form-label">Status</label><select class="form-select"><option selected>Active</option><option>Onboarding</option><option>Paused</option><option>Archived</option></select></div><div class="col-md-4"><label class="form-label">Account Manager</label><select class="form-select"><option selected>Abhishek Kapoor</option><option>Priya Verma</option><option>Neha Singh</option></select></div><div class="col-md-4"><label class="form-label">Client Logo / Avatar</label><input class="form-control" type="file" accept="image/*"></div>
        </div>
        <hr class="my-4"><h2 class="h5 fw-bold mb-3">Project & Payment Details</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Service / Project</label><input class="form-control" value="Website Development"></div><div class="col-md-3"><label class="form-label">Project Price (₹)</label><input id="editProjectPrice" class="form-control" type="number" value="80000"></div><div class="col-md-3"><label class="form-label">Payment Terms</label><input id="editPaymentTerms" class="form-control" value="50% advance / 50% final" readonly></div><div class="col-md-4"><label class="form-label">Start Date</label><input class="form-control" type="date" value="2025-09-15"></div><div class="col-md-4"><label class="form-label">End Date / Deadline</label><input class="form-control" type="date" value="2025-10-30"></div><div class="col-md-4"><label class="form-label">Invoice Number</label><input class="form-control" value="INV-2025-001"></div><div class="col-md-6"><label class="form-label">Advance Payment</label><input id="editAdvance" class="form-control" value="₹40,000" readonly></div><div class="col-md-6"><label class="form-label">Final Payment</label><input id="editFinal" class="form-control" value="₹40,000" readonly></div><div class="col-12"><div id="editPaymentRule" class="client-payment-rule">Payment rule: 50% advance and 50% after project completion.</div></div></div>
        <div class="d-flex justify-content-end gap-2 mt-4"><button type="button" class="btn btn-outline-secondary rounded-pill px-4 py-2">Cancel</button><button type="submit" class="btn btn-brand rounded-pill px-4 py-2 fw-semibold">Save Changes</button></div>
    </form></section>
</section>
<script>document.addEventListener('DOMContentLoaded',function(){const price=document.getElementById('editProjectPrice');const terms=document.getElementById('editPaymentTerms');const advance=document.getElementById('editAdvance');const final=document.getElementById('editFinal');const rule=document.getElementById('editPaymentRule');price.addEventListener('input',function(){const amount=Number(price.value||0);const rate=amount>0&&amount<10000?60:50;const upfront=amount*rate/100;terms.value=rate+'% advance / '+(100-rate)+'% final';advance.value=amount?'₹'+upfront.toLocaleString('en-IN'):'';final.value=amount?'₹'+(amount-upfront).toLocaleString('en-IN'):'';rule.textContent=rate===60?'Payment rule: projects below ₹10,000 require 60% upfront and 40% after completion.':'Payment rule: 50% advance and 50% after project completion.';});});</script>
@endsection
