@php
    $client = $client ?? 'dreamhome-real-estate';
    $clientNames = ['dreamhome-real-estate' => 'DreamHome Real Estate Pvt. Ltd.', 'nexus-property-group' => 'Nexus Property Group', 'medicore-health' => 'MediCore Health', 'northstar-growth' => 'Northstar Growth'];
    $clientName = $clientNames[$client] ?? $clientNames['dreamhome-real-estate'];
@endphp
@extends('layouts.team', ['title' => 'Add Client Work', 'description' => 'Set up a service, project, delivery plan, and payment flow for this client.'])
@section('content')
<section class="dashboard-content client-work-page">
    <div class="dashboard-welcome-row align-items-center justify-content-between"><div><h1>Add Client Work</h1><p>Set up the service flow for <strong>{{ $clientName }}</strong>.</p></div><div class="d-flex gap-2 ms-auto" style="grid-column: 3; justify-self: end;"><a href="{{ route('team.clients.detail', $client) }}" class="btn btn-outline-secondary rounded-pill px-4 py-2">Back to Client</a></div></div>
    <section class="dashboard-card mt-3 p-4"><form>
        <h2 class="h5 fw-bold mb-3">1. Service & Client Need</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Service</label><select class="form-select"><option>Website Development</option><option>SEO</option><option>Digital Marketing</option><option>Software Development</option><option>Branding & Design</option><option>Google Ads</option></select></div><div class="col-md-6"><label class="form-label">Work Status</label><select class="form-select"><option>Planning</option><option>In Progress</option><option>On Hold</option><option>Completed</option></select></div><div class="col-12"><label class="form-label">What does the client want?</label><textarea class="form-control" rows="3" placeholder="Example: More qualified property enquiries, a trustworthy online presence, and a simple enquiry flow."></textarea></div><div class="col-12"><label class="form-label">What are we handling?</label><textarea class="form-control" rows="3" placeholder="Explain the exact scope: website pages, SEO, campaigns, CRM, branding, or other work."></textarea></div></div>
        <hr class="my-4"><h2 class="h5 fw-bold mb-3">2. Delivery Model & Key Points</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Delivery Model</label><input class="form-control" value="Strategy → Design → Develop → Launch"></div><div class="col-md-6"><label class="form-label">Assigned Team</label><input class="form-control" placeholder="Abhishek Kapoor, Neha Singh"></div><div class="col-12"><label class="form-label">Key Points</label><textarea class="form-control" rows="5" placeholder="One key point per line&#10;Responsive website&#10;SEO-ready structure&#10;Analytics and secure hosting"></textarea></div></div>
        <hr class="my-4"><h2 class="h5 fw-bold mb-3">3. Timeline, Price & Payment</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Start Date</label><input class="form-control" type="date"></div><div class="col-md-4"><label class="form-label">End Date / Deadline</label><input class="form-control" type="date"></div><div class="col-md-4"><label class="form-label">Project Price (₹)</label><input id="workPrice" class="form-control" type="number" placeholder="80000"></div><div class="col-md-4"><label class="form-label">Payment Terms</label><input id="workTerms" class="form-control" value="50% advance / 50% final" readonly></div><div class="col-md-4"><label class="form-label">Advance Amount</label><input id="workAdvance" class="form-control" readonly></div><div class="col-md-4"><label class="form-label">Final Amount</label><input id="workFinal" class="form-control" readonly></div><div class="col-md-6"><label class="form-label">Invoice Number</label><input class="form-control" placeholder="INV-2025-001"></div><div class="col-md-6"><label class="form-label">Payment Status</label><select class="form-select"><option>Advance Pending</option><option>Advance Paid</option><option>Final Pending</option><option>Fully Paid</option></select></div><div class="col-12"><div id="workRule" class="client-payment-rule">50% advance and 50% after project completion.</div></div></div>
        <div class="d-flex justify-content-end gap-2 mt-4"><button type="button" class="btn btn-outline-secondary rounded-pill px-4 py-2">Save Draft</button><button type="submit" class="btn btn-brand rounded-pill px-4 py-2 fw-semibold">Add Client Work</button></div>
    </form></section>
</section>
<script>document.addEventListener('DOMContentLoaded',function(){const price=document.getElementById('workPrice');price.addEventListener('input',function(){const amount=Number(price.value||0);const rate=amount>0&&amount<10000?60:50;const advance=amount*rate/100;document.getElementById('workTerms').value=rate+'% advance / '+(100-rate)+'% final';document.getElementById('workAdvance').value=amount?'₹'+advance.toLocaleString('en-IN'):'';document.getElementById('workFinal').value=amount?'₹'+(amount-advance).toLocaleString('en-IN'):'';document.getElementById('workRule').textContent=rate===60?'Under ₹10,000: 60% upfront and 40% after completion.':'50% advance and 50% after project completion.';});});</script>
@endsection
