@extends('layouts.team', ['title' => 'Nivara Finance Dashboard', 'description' => 'Project details, delivery status, billing, gallery, and team activity.'])
@section('content')
<section class="dashboard-content project-admin-detail">
    <div class="project-admin-breadcrumb"><a href="{{ route('team.projects') }}">Projects</a><i class="bi bi-chevron-right"></i><span>Nivara Finance Dashboard</span></div>
    <div class="project-admin-head"><div><div class="project-admin-title"><span class="project-admin-icon"><i class="bi bi-window-stack"></i></span><div><h1>Nivara Finance Dashboard <span class="dash-status published">Published</span></h1><p>Software <span>|</span> Added on 12 Sep 2025 <span>|</span> Client: DreamHome Real Estate</p></div></div></div><div class="project-admin-actions"><a href="{{ route('team.projects.create') }}" class="btn btn-light border"><i class="bi bi-pencil me-1"></i> Edit Project</a><button class="btn btn-light border"><i class="bi bi-file-earmark-text me-1"></i> Create Proposal</button><a href="{{ route('team.clients.detail', 'dreamhome-real-estate') }}" class="btn btn-brand">View Client</a></div></div>
    <nav class="project-admin-tabs"><a class="active" href="#overview">Overview</a><a href="#delivery">Delivery</a><a href="#billing">Billing</a><a href="#gallery">Gallery</a><a href="#technology">Technology</a><a href="#activity">Activity</a></nav>
    <div class="row g-3 mt-1" id="overview"><div class="col-lg-8"><section class="dashboard-card project-admin-panel h-100"><h2>Project Overview</h2><p>A secure finance dashboard for tracking invoices, cash flow, approvals, and team operations. The project gives DreamHome Real Estate a clearer way to manage financial work.</p><div class="project-challenge-solution"><div><h3>The Challenge</h3><p>Finance operations were spread across disconnected tools, making reporting and approvals slow.</p></div><div><h3>Our Solution</h3><p>We built a clean dashboard with structured workflows, reports, and secure team access.</p></div></div></section></div><div class="col-lg-4"><section class="dashboard-card project-admin-panel h-100"><h2>Project Snapshot</h2><dl class="project-admin-dl"><div><dt>Category</dt><dd>Software</dd></div><div><dt>Status</dt><dd><span class="project-state in-progress">In Progress</span></dd></div><div><dt>Start Date</dt><dd>15 Sep 2025</dd></div><div><dt>Deadline</dt><dd>30 Oct 2025</dd></div><div><dt>Price</dt><dd>₹80,000</dd></div><div><dt>Team</dt><dd>04 Members</dd></div></dl></section></div></div>
    <div class="row g-3 mt-0" id="delivery"><div class="col-lg-7"><section class="dashboard-card project-admin-panel"><div class="project-admin-panel-title"><h2>Delivery Progress</h2><strong>65%</strong></div><div class="project-progress"><span style="width:65%"></span></div><div class="project-delivery-steps">@foreach([['01','Discover','Complete'],['02','Plan','Complete'],['03','Design','In Progress'],['04','Develop','Upcoming'],['05','Launch','Upcoming']] as $step)<div class="{{ Str::slug($step[2]) }}"><b>{{ $step[0] }}</b><i class="bi {{ $step[2] === 'Complete' ? 'bi-check-circle-fill' : 'bi-circle' }}"></i><strong>{{ $step[1] }}</strong><small>{{ $step[2] }}</small></div>@endforeach</div></section></div><div class="col-lg-5"><section class="dashboard-card project-admin-panel"><h2>Key Features</h2><ul class="project-admin-list">@foreach(['Invoice tracking and reports','Approval workflows','Secure role-based access','Responsive dashboard UI','Analytics and lead tracking'] as $feature)<li><i class="bi bi-check-circle-fill"></i>{{ $feature }}</li>@endforeach</ul></section></div></div>
    <div class="row g-3 mt-0" id="billing"><div class="col-lg-7"><section class="dashboard-card project-admin-panel"><div class="project-admin-panel-title"><h2>Payment & Invoices</h2><span class="client-payment-rule">50% advance / 50% final</span></div><div class="payment-summary"><div><small>Contract Value</small><strong>₹80,000</strong></div><div><small>Advance Paid</small><strong class="payment-paid">₹40,000</strong><span>50% paid</span></div><div><small>Balance Due</small><strong class="payment-due">₹40,000</strong><span>Due on completion</span></div></div><div class="invoice-list"><div class="invoice-row"><i class="bi bi-file-earmark-text"></i><span><strong>INV-2025-017</strong><small>Nivara Finance Dashboard - Advance · 15 Sep 2025</small></span><b>₹40,000</b><em class="paid">Paid</em></div><div class="invoice-row"><i class="bi bi-file-earmark-text"></i><span><strong>INV-2025-018</strong><small>Nivara Finance Dashboard - Final · 30 Oct 2025</small></span><b>₹40,000</b><em>Pending</em></div></div><button class="btn btn-sm btn-outline-brand rounded-pill mt-3">+ Create Invoice</button></section></div><div class="col-lg-5"><section class="dashboard-card project-admin-panel h-100"><h2>Technologies Used</h2><div class="project-tech-pills">@foreach(['Laravel','Bootstrap','JavaScript','MySQL','REST API','Analytics'] as $tech)<span>{{ $tech }}</span>@endforeach</div></section></div></div>
    <section class="dashboard-card project-admin-panel mt-0" id="gallery"><div class="project-admin-panel-title"><h2>Project Gallery</h2><a href="#" class="btn btn-sm btn-light border">+ Upload Screenshot</a></div><div class="project-admin-gallery"><div><img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=85" alt="Dashboard homepage"><small>Dashboard Homepage</small></div><div><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85" alt="Invoice screen"><small>Invoice Management</small></div><div><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=85" alt="Analytics screen"><small>Analytics Reports</small></div></div></section>
    <div class="row g-3 mt-0" id="activity"><div class="col-lg-6"><section class="dashboard-card project-admin-panel"><h2>Client Testimonial</h2><p class="project-quote">“The dashboard has made our financial workflow much clearer and easier for the whole team.”</p><strong>Amit Sharma</strong><small class="d-block text-secondary">Founder, DreamHome Real Estate</small></section></div><div class="col-lg-6"><section class="dashboard-card project-admin-panel"><div class="project-admin-panel-title"><h2>Recent Activity</h2><a href="#">View All →</a></div><div class="client-activity"><div><i></i><span><strong>Requirement updated</strong><small>Added approval workflow requirements</small></span><time>2 hours ago</time></div><div><i></i><span><strong>Design approved</strong><small>Client approved the dashboard layout</small></span><time>Yesterday</time></div><div><i></i><span><strong>Invoice paid</strong><small>Advance payment received</small></span><time>2 days ago</time></div></div></section></div></div>
</section>
@endsection
